name: TDR Tag and pre deploy
on:
  workflow_dispatch:
  push:
    branches:
      - create-signed-cookies-lambda
      - master
jobs:
  pre-deploy:
    uses: nationalarchives/tdr-github-actions/.github/workflows/lambda_build.yml@main
    with:
      repo-name: tdr-antivirus
      artifact-name: function
      artifact-file-type: zip
      artifact-path: lambda
      build-command: |
        mkdir lambda
        cd lambda
        cp ../src/signed_cookies.py .
        pip install --target ./package -r ../requirements-runtime.txt
        cd package
        zip -r ../function.zip .
        cd ..
        zip -g function.zip signed_cookies.py
        cd ..
    secrets:
      MANAGEMENT_ACCOUNT: ${{ secrets.MANAGEMENT_ACCOUNT }}
      WORKFLOW_PAT: ${{ secrets.WORKFLOW_PAT }}
  deploy:
    needs: pre-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: gh workflow run deploy.yml -f environment=intg -f to-deploy=${{ needs.pre-deploy.outputs.next-version }} --ref create-signed-cookies-lambda
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_PAT }}
