name: TDR Run Lambda Tests
on:
  pull_request:
  push:
    branches-ignore:
      - main
      - release-*
permissions:
  id-token: write
  contents: write
jobs:
  test:
    uses: nationalarchives/tdr-github-actions/.github/workflows/tdr_test.yml@b469512bc31f0425270a12b87ebe68807c3a1daf # v0.0.46
    with:
      repo-name: tdr-signed-cookies
      test-command: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        python -m pytest
    secrets:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
